#!/usr/bin/env python3
"""Refresh only Ask Matt, applying the approved AskPit identity and writer route."""
import argparse
import hashlib
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'skills/core/ask-pit'
REPOSITORY = 'https://github.com/mattpocock/skills.git'
SOURCE_PATH = 'skills/engineering/ask-matt'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def adapt(data):
    text = data.decode('utf-8')
    if not re.search(r'^name: ask-matt$', text, re.M):
        raise ValueError('Ask Matt identity changed; review required')
    if '/writing-for-agents' not in text:
        raise ValueError('Writing for Agents route missing; review required')
    text = re.sub(r'^name: ask-matt$', 'name: ask-pit', text, count=1, flags=re.M)
    text = text.replace('/writing-for-agents', '/writing-for-astra')
    return text.encode('utf-8')


def refresh(checkout, destination=DEST):
    checkout, destination = Path(checkout), Path(destination)
    source = checkout / SOURCE_PATH
    files = {}
    for path in sorted(source.rglob('*')):
        if path.is_symlink():
            raise ValueError('Upstream symlink requires review: ' + str(path.relative_to(source)))
        if path.is_file():
            files[str(path.relative_to(source))] = path.read_bytes()
    if 'SKILL.md' not in files:
        raise ValueError('Ask Matt source missing; existing AskPit preserved')
    files['LICENSE'] = (checkout / 'LICENSE').read_bytes()
    if any(key in files for key in ('UPSTREAM.json', 'PROVENANCE.md')):
        raise ValueError('Upstream provenance filename collision; review required')
    original = dict(files)
    files['SKILL.md'] = adapt(files['SKILL.md'])
    # Packaging metadata only; workflow instructions remain upstream verbatim.
    yaml = 'agents/openai.yaml'
    if yaml in files:
        text = files[yaml].decode('utf-8')
        text, count = re.subn(r'(?m)^(  display_name: )"Ask Matt"$', r'\1"AskPit"', text)
        if count != 1:
            raise ValueError('Upstream UI identity changed; review required')
        files[yaml] = text.encode('utf-8')
    commit = subprocess.check_output(['git', '-C', str(checkout), 'rev-parse', 'HEAD'], text=True).strip()
    record = {'repository': REPOSITORY, 'source_path': SOURCE_PATH, 'commit': commit,
              'upstream_sha256': {k: digest(v) for k, v in original.items()},
              'generated_sha256': {k: digest(v) for k, v in files.items()}}
    files['UPSTREAM.json'] = (json.dumps(record, indent=2) + '\n').encode()
    files['PROVENANCE.md'] = (f'''# AskPit provenance

Adapted from Matt Pocock's Ask Matt under the included MIT license.
Source: {REPOSITORY}
Path: {SOURCE_PATH}
Commit: {commit}

Only behavioral adaptation: /writing-for-agents routes to /writing-for-astra.
Packaging adaptations: skill name ask-pit and display name AskPit.
All remaining workflow text and supporting files follow upstream unchanged.
AskPit is explicit-only, as configured by upstream in agents/openai.yaml.
Writing for Astra is maintained separately; it is never overwritten by this sync.
This is one adapted skill, not a mirror of the Matt Pocock skill family.

Generated by scripts/sync-ask-pit.py. A missing route or changed identity stops
the update for review and leaves the current generated skill untouched.
UPSTREAM.json records hashes for original and generated files.

## Why these adaptations exist

The writer route selects our authoring rules based on
[OpenAI Astra guidance](https://developers.openai.com/blog/rethinking-skills-and-prompts-for-gpt-6-astra).
This avoids reintroducing the original writer's forced recipes and context
sequences. Ask Matt's own orchestration remains intact by operator choice.
The name/display changes distinguish this adaptation from upstream Ask Matt.

## Update review

The daily Review adapted skill upstreams workflow opens or updates a GitHub
issue when this source package or its license changes. It never rewrites the
skill or advances the accepted baseline. Run this generator only as part of
an approved upstream review; inspect its full diff before merging.
See [Writing for Astra provenance](../../engineering/writing-for-astra/PROVENANCE.md)
for the authoring adaptations and their rationale.
''').encode()
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='.ask-pit-', dir=destination.parent) as temp:
        stage = Path(temp) / 'skill'
        stage.mkdir()
        for name, data in files.items():
            path = stage / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        validate(stage)
        backup = Path(temp) / 'previous'
        if destination.exists():
            destination.rename(backup)
        try:
            stage.rename(destination)
        except BaseException:
            if backup.exists():
                backup.rename(destination)
            raise
    print('ask_pit_synced commit=' + commit)


def validate(destination=DEST):
    destination = Path(destination)
    record = json.loads((destination / 'UPSTREAM.json').read_text())
    expected = set(record['generated_sha256']) | {'UPSTREAM.json', 'PROVENANCE.md'}
    actual = {str(p.relative_to(destination)) for p in destination.rglob('*') if p.is_file()}
    if actual != expected:
        raise ValueError('AskPit file inventory differs from recorded generation')
    for name, sha in record['generated_sha256'].items():
        if digest((destination / name).read_bytes()) != sha:
            raise ValueError('AskPit generated content changed: ' + name)
    for name, sha in record['upstream_sha256'].items():
        data = (destination / name).read_bytes()
        if name == 'SKILL.md':
            text = data.decode().replace('/writing-for-astra', '/writing-for-agents')
            data = re.sub(r'^name: ask-pit$', 'name: ask-matt', text, count=1, flags=re.M).encode()
        elif name == 'agents/openai.yaml':
            data = data.replace(b'  display_name: "AskPit"', b'  display_name: "Ask Matt"')
        if digest(data) != sha:
            raise ValueError('Unapproved upstream difference: ' + name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--upstream', type=Path, help='Existing upstream checkout for local validation')
    parser.add_argument('--check', action='store_true', help='Validate committed generated files without network')
    args = parser.parse_args()
    if args.check:
        validate()
        print('ask_pit_valid')
    elif args.upstream:
        refresh(args.upstream)
    else:
        with tempfile.TemporaryDirectory(prefix='ask-pit-upstream-') as temp:
            subprocess.run(['git', 'clone', '--depth', '1', '--branch', 'main', REPOSITORY, temp], check=True)
            refresh(Path(temp))


if __name__ == '__main__':
    main()
